### ISSUE TITLE
I was trying to use audio but I don't know correct configuration can u help me with pulseAudio

### ISSUE THREAD

**Issue by hachimetsu** [JamesCullum/flutter-adb-template#1]
here : https://github.com/hachimetsu/gitpod-GUI.git
pulseAudio refuse to start/respawn.
![image](https://github.com/JamesCullum/flutter-adb-template/assets/107677571/5d54f326-26b1-4788-ba05-86a8bf160ddf)

**Comment by JamesCullum** [comment]
Don't think this is the right forum for this question - maybe try contacting their support or StackOverflow 👍
